// Hand-written preamble. bindgen.sjson points at this file via `imports_file`, so odin-c-bindgen pastes
// it verbatim near the top of the generated sciter.odin, just under the `package sciter` line. Edit it
// here, not in sciter.odin - that file is regenerated by `just bindgen`.
//
// Everything below exists because Sciter is reached through a function-pointer table rather than through
// linked symbols. The shared library exports exactly one thing:
//
//     $ nm -D --defined-only libsciter.so | grep -w SciterAPI
//     00000000007e4a19 T SciterAPI
//
// `SciterAPI()` returns a `^Isciter_Api`, and every other call in these bindings is a field of it. So
// there is no `foreign import` here - the library is opened at runtime with core:dynlib, and `load()`
// must be called once before anything else.

import "core:dynlib"
import "core:fmt"
import "core:os"
import "core:path/filepath"
import "core:strings"

// The name of the shared library on each platform, from SCITER_DLL_NAME in sciter-x-types.h.
LIBRARY_NAME :: "sciter.dll" when ODIN_OS == .Windows else "libsciter.dylib" when ODIN_OS == .Darwin else "libsciter.so"

// Accepted values of `Isciter_Api.version`. A value outside this set means the ISciterAPI struct these
// bindings were generated from is not the one the loaded library implements: the field offsets would be
// wrong and every call would jump into the wrong slot. That produces a crash with no explanation, so
// `load` refuses instead.
//
// `SCITER_API_VERSION` is generated straight from the vendored sciter-x-api.h, so it always describes
// the headers these bindings were built from.
EXPECTED_API_VERSION :: SCITER_API_VERSION

// The result of every DOM call in ISciterAPI.
//
// This is hand-written rather than generated because upstream never made it a type: sciter-x-dom.h has
// `#define SCDOM_RESULT INT` and six more `#define`s for the values, so clang only ever sees an `int`
// return and a handful of unrelated integer constants. bindgen's `enumify_macros` would collect them,
// but it builds the enum over Odin's `int` (8 bytes), and these functions return a 4-byte C `int` - the
// upper half of the returned register would be read as part of the value. Hence `enum Int` here, and
// the `procedure_type_overrides` table in bindgen.sjson to put it on all 101 slots that return it.
//
// The `#define`s themselves are removed in bindgen.sjson, so this is the only spelling of them.
Scdom_Result :: enum Int {
	OK                = 0,
	INVALID_HWND      = 1,  // invalid HWINDOW
	INVALID_HANDLE    = 2,  // invalid HELEMENT
	PASSIVE_HANDLE    = 3,  // attempt to use an HELEMENT not marked by Sciter_UseElement()
	INVALID_PARAMETER = 4,  // parameter is invalid, e.g. a null pointer
	OPERATION_FAILED  = 5,  // operation failed, e.g. invalid html in SciterSetElementHtml()
	OK_NOT_HANDLED    = -1, // not an error: the call succeeded and nothing consumed it
}

// The virtual keys the engine reports, and the ones it accepts.
//
// `SC_KB_CODES` in `external/sciter/include/sciter-x-key-codes.h`, transcribed by hand. Nothing in the
// SDK includes that header - not `sciter-x.h`, not `sciter-x-api.h`, nothing - so it is not reached
// transitively and `src/flatten_headers.py` cannot pick it up for free either: adding it to that list
// is the generated alternative to this block, and it is the right move the next time bindings are
// regenerated on Linux (`just bindgen` refuses on Windows and macOS, so a Windows-only change cannot
// produce the byte-identical sciter.odin that `.github/workflows/bindgen.yml` asserts - though it CAN
// be made to, measured, and what it takes is written up in docs/PLAN.md section 12). The type name
// here is the one bindgen would emit from the C tag, so that migration is a delete rather than a
// rename; the members are the `KB_*` names with the prefix stripped, which is also what bindgen's
// shared-prefix pass does.
//
// **These are GLFW-style codes and NOT platform virtual keys**, and the engine translates for you.
// Measured on 6.0.4.9, Windows, by posting real `WM_KEYDOWN` messages to a live window: `VK_RETURN`
// (13) arrives at both a host `Key_Event.key_code` and script's `event.keyCode` as **257**, `VK_UP`
// (38) as 265, `VK_DOWN` (40) as 264, `VK_ESCAPE` (27) as 256, `VK_DELETE` (46) as 261, `VK_F1` (112)
// as 290. Only the printable ASCII range coincides - `A` is 65 in both sets, which is what makes the
// mistake survive a letters-only test.
//
// `windowless_key` is the other direction and does NO translation: whatever code the host passes is
// what the document sees. Measured with the same page - code 257 gives a `keydown` with
// `event.code == "Enter"`, code 13 gives one whose `event.code` is undefined, so the key is delivered
// and recognised as nothing. That is why a windowless host must send from this set (`sciter-x-msg.h`
// says only "key code" and there is nothing in the docs tree about it either).
//
// Two more measurements worth having before comparing against this enum: the editing keys are consumed
// by the intrinsic behavior when an `<input>` has the focus (`.DELETE` and `.BACKSPACE` reached a host
// handler but raised no script `keydown` at all), and `.CHAR` carries a CHARACTER rather than a key -
// `windowless_key(view, .CHAR, 120)` types an `x`.
Sc_Kb_Codes :: enum u32 {
	UNKNOWN       = 0,

	// Printable keys. The values are the ASCII codes of the unshifted characters, which is why they
	// look like - and for letters and digits are - the platform virtual keys.
	SPACE         = 32,
	QUOTE         = 39, // '
	APOSTROPHE    = 39, // the header's own alias for QUOTE
	COMMA         = 44, // ,
	MINUS         = 45, // -
	PERIOD        = 46, // .
	SLASH         = 47, // /
	NUM_0         = 48, // KB_0 upstream; Odin identifiers cannot start with a digit
	NUM_1         = 49,
	NUM_2         = 50,
	NUM_3         = 51,
	NUM_4         = 52,
	NUM_5         = 53,
	NUM_6         = 54,
	NUM_7         = 55,
	NUM_8         = 56,
	NUM_9         = 57,
	SEMICOLON     = 59, // ;
	EQUAL         = 61, // =
	A             = 65,
	B             = 66,
	C             = 67,
	D             = 68,
	E             = 69,
	F             = 70,
	G             = 71,
	H             = 72,
	I             = 73,
	J             = 74,
	K             = 75,
	L             = 76,
	M             = 77,
	N             = 78,
	O             = 79,
	P             = 80,
	Q             = 81,
	R             = 82,
	S             = 83,
	T             = 84,
	U             = 85,
	V             = 86,
	W             = 87,
	X             = 88,
	Y             = 89,
	Z             = 90,
	LEFT_BRACKET  = 91, // [
	BACKSLASH     = 92, // 	RIGHT_BRACKET = 93, // ]
	GRAVE_ACCENT  = 96, // `
	BACKQUOTE     = 96, // the header's own alias for GRAVE_ACCENT
	WORLD_1       = 161, // non-US #1
	WORLD_2       = 162, // non-US #2

	// Function keys. Nothing here coincides with a platform virtual key.
	ESCAPE        = 256,
	ENTER         = 257,
	TAB           = 258,
	BACKSPACE     = 259,
	INSERT        = 260,
	DELETE        = 261,
	RIGHT         = 262,
	LEFT          = 263,
	DOWN          = 264,
	UP            = 265,
	PAGE_UP       = 266,
	PAGE_DOWN     = 267,
	HOME          = 268,
	END           = 269,
	CAPS_LOCK     = 280,
	SCROLL_LOCK   = 281,
	NUM_LOCK      = 282,
	PRINT_SCREEN  = 283,
	PAUSE         = 284,
	F1            = 290,
	F2            = 291,
	F3            = 292,
	F4            = 293,
	F5            = 294,
	F6            = 295,
	F7            = 296,
	F8            = 297,
	F9            = 298,
	F10           = 299,
	F11           = 300,
	F12           = 301,
	F13           = 302,
	F14           = 303,
	F15           = 304,
	F16           = 305,
	F17           = 306,
	F18           = 307,
	F19           = 308,
	F20           = 309,
	F21           = 310,
	F22           = 311,
	F23           = 312,
	F24           = 313,
	F25           = 314,
	KP_0          = 320,
	KP_1          = 321,
	KP_2          = 322,
	KP_3          = 323,
	KP_4          = 324,
	KP_5          = 325,
	KP_6          = 326,
	KP_7          = 327,
	KP_8          = 328,
	KP_9          = 329,
	KP_DECIMAL    = 330,
	KP_DIVIDE     = 331,
	KP_MULTIPLY   = 332,
	KP_SUBTRACT   = 333,
	KP_ADD        = 334,
	KP_ENTER      = 335,
	KP_EQUAL      = 336,
	LEFT_SHIFT    = 340,
	LEFT_CONTROL  = 341,
	LEFT_ALT      = 342,
	LEFT_SUPER    = 343,
	RIGHT_SHIFT   = 344,
	RIGHT_CONTROL = 345,
	RIGHT_ALT     = 346,
	RIGHT_SUPER   = 347,
	MENU          = 348,
	CONTEXT_MENU  = 349,
}

// `KB_KEY_LAST`, the header's last-value marker. A constant rather than a member, because as a member
// it would be a second name for CONTEXT_MENU in every switch and every `fmt` of the enum.
KB_KEY_LAST :: Sc_Kb_Codes.CONTEXT_MENU

@(private = "file")
g_api: ^Isciter_Api

@(private = "file")
g_library: dynlib.Library

Load_Error :: enum {
	None,
	Already_Loaded,
	Library_Not_Found,
	Missing_Entry_Point,
	Null_Api,
	Version_Mismatch,
}

// Returns the engine's function table. Panics if `load` has not been called - calling through a nil
// table would fault somewhere deep inside the bindings with no indication of the real cause.
api :: proc(loc := #caller_location) -> ^Isciter_Api {
	fmt.assertf(g_api != nil, "sciter.load() must be called before any other sciter call", loc = loc)
	return g_api
}

// True once `load` has succeeded.
loaded :: proc() -> bool {
	return g_api != nil
}

// Opens the Sciter shared library and fetches its API table. Call once, before anything else.
//
// `path` may be a full path to the library file or a directory containing it; leave it empty to search.
// The search order is deliberately explicit, because "it did not load" is the most common first-run
// problem with Sciter and a bare dlopen error says nothing useful:
//
//  1. `path`, if given
//  2. the SCITER_LIB environment variable (a file or a directory)
//  3. the directory containing the running executable
//  4. `lib/<platform>/` relative to the current directory, where this repository keeps its copy
//  5. the system library search path (LD_LIBRARY_PATH / PATH / DYLD_LIBRARY_PATH)
//
// `tried` lists every candidate that was attempted, so the caller can print something actionable. It
// is allocated with `allocator` **and returned on every path, success included** - each string
// separately allocated - so the caller owns it and has to free it either way. `load_engine` in
// `package sciter_app` is the worked example.
load :: proc(
	path := "",
	allocator := context.allocator,
) -> (
	err: Load_Error,
	tried: []string,
) {
	if g_api != nil {
		return .Already_Loaded, nil
	}

	candidates := make([dynamic]string, allocator)

	add :: proc(candidates: ^[dynamic]string, dir_or_file: string) {
		if dir_or_file == "" {
			return
		}
		if filepath.base(dir_or_file) == LIBRARY_NAME {
			append(candidates, strings.clone(dir_or_file, candidates.allocator))
		} else {
			joined, join_err := filepath.join({dir_or_file, LIBRARY_NAME}, candidates.allocator)
			if join_err == nil {
				append(candidates, joined)
			}
		}
	}

	add(&candidates, path)

	if env, has_env := os.lookup_env("SCITER_LIB", context.temp_allocator); has_env {
		add(&candidates, env)
	}

	// Alongside the executable. os.args[0] is what the process was invoked as, so this is best-effort:
	// it resolves to "." for a bare-name invocation, which is a harmless extra candidate.
	//
	// `filepath.dir` is `os.dir`, which slices rather than allocates: the result points into
	// `os.args[0]` and must not be freed. `add` clones what it is given into the candidates allocator,
	// so nothing here outlives the call.
	//
	// **This block had drifted from the generated file.** It read `filepath.dir(os.args[0],
	// context.temp_allocator)` - an allocator argument that procedure does not take - with a comment
	// claiming it allocated. `sciter.odin` carried the correct one-argument call, so nothing ever
	// compiled this version and the error sat here unnoticed. `just bindgen` pastes this file verbatim,
	// so regenerating would have turned it into a build failure.
	if len(os.args) > 0 {
		add(&candidates, filepath.dir(os.args[0]))
	}

	when ODIN_OS == .Windows {
		add(&candidates, "lib/windows/x64")
	} else when ODIN_OS == .Darwin {
		add(&candidates, "lib/macosx")
	} else {
		add(&candidates, "lib/linux/x64")
	}

	// Last resort: bare name, resolved by the system loader.
	append(&candidates, strings.clone(LIBRARY_NAME, allocator))

	library: dynlib.Library
	found: bool
	for candidate in candidates {
		if library, found = dynlib.load_library(candidate); found {
			break
		}
	}
	if !found {
		return .Library_Not_Found, candidates[:]
	}

	symbol, has_symbol := dynlib.symbol_address(library, "SciterAPI")
	if !has_symbol {
		dynlib.unload_library(library)
		return .Missing_Entry_Point, candidates[:]
	}

	table := (cast(Sciter_Api_Ptr)symbol)()
	if table == nil {
		dynlib.unload_library(library)
		return .Null_Api, candidates[:]
	}
	if table.version != EXPECTED_API_VERSION {
		dynlib.unload_library(library)
		return .Version_Mismatch, candidates[:]
	}

	g_library = library
	g_api = table
	return .None, candidates[:]
}

// Takes an ISciterAPI table that something else already has, instead of opening the library.
//
// This is what a **native extension** calls. An extension is a shared library that the engine itself
// loads, in response to script's `sciter.loadLibrary("name")`, through one exported entry point:
//
//	SBOOL SCAPI SciterLibraryInit(ISciterAPI* psapi, SCITER_VALUE* plibobject)
//
// The host hands over the table there - the library is already open, and `load` would be both wrong
// and wasteful. Everything after this call works exactly as if `load` had succeeded: `api()` returns
// the table, and every wrapper built on it works unchanged.
//
// The version check is the same one `load` makes, and matters more here rather than less: the host
// decides which engine is running, so an extension can be handed a table it was not generated against.
//
// See `examples/extension.odin`.
adopt :: proc(table: ^Isciter_Api) -> Load_Error {
	if g_api != nil {
		return .Already_Loaded
	}
	if table == nil {
		return .Null_Api
	}
	if table.version != EXPECTED_API_VERSION {
		return .Version_Mismatch
	}
	g_api = table
	return .None
}

// Releases the shared library. Rarely needed - the engine is normally kept for the life of the process.
unload :: proc() {
	if g_api == nil {
		return
	}
	g_api = nil

	// Nothing to unload when the table came from `adopt`: the host owns the library, not us.
	if g_library != nil {
		dynlib.unload_library(g_library)
		g_library = {}
	}
}
