// Hand-written preamble. bindgen.sjson points at this file via `imports_file`, so odin-c-bindgen pastes
// it verbatim near the top of the generated sciter.odin, just under the `package sciter` line. Edit it
// here, not in sciter.odin - that file is regenerated by `just bindgen`.
//
// Everything below exists because Sciter is reached through a function-pointer table rather than through
// linked symbols. The shared library exports exactly one thing:
//
//     $ nm -D --defined-only libsciter.so | grep -w SciterAPI
//     00000000007e4a19 T SciterAPI
//
// `SciterAPI()` returns a `^Isciter_Api`, and every other call in these bindings is a field of it. So
// there is no `foreign import` here - the library is opened at runtime with core:dynlib, and `load()`
// must be called once before anything else.

import "core:dynlib"
import "core:fmt"
import "core:os"
import "core:path/filepath"
import "core:strings"

// The name of the shared library on each platform, from SCITER_DLL_NAME in sciter-x-types.h.
LIBRARY_NAME :: "sciter.dll" when ODIN_OS == .Windows else "libsciter.dylib" when ODIN_OS == .Darwin else "libsciter.so"

// Accepted values of `Isciter_Api.version`. A value outside this set means the ISciterAPI struct these
// bindings were generated from is not the one the loaded library implements: the field offsets would be
// wrong and every call would jump into the wrong slot. That produces a crash with no explanation, so
// `load` refuses instead.
//
// `SCITER_API_VERSION` is generated straight from the vendored sciter-x-api.h, so it always describes
// the headers these bindings were built from.
EXPECTED_API_VERSION :: SCITER_API_VERSION

@(private = "file")
g_api: ^Isciter_Api

@(private = "file")
g_library: dynlib.Library

Load_Error :: enum {
	None,
	Already_Loaded,
	Library_Not_Found,
	Missing_Entry_Point,
	Null_Api,
	Version_Mismatch,
}

// Returns the engine's function table. Panics if `load` has not been called - calling through a nil
// table would fault somewhere deep inside the bindings with no indication of the real cause.
api :: proc(loc := #caller_location) -> ^Isciter_Api {
	fmt.assertf(g_api != nil, "sciter.load() must be called before any other sciter call", loc = loc)
	return g_api
}

// True once `load` has succeeded.
loaded :: proc() -> bool {
	return g_api != nil
}

// Opens the Sciter shared library and fetches its API table. Call once, before anything else.
//
// `path` may be a full path to the library file or a directory containing it; leave it empty to search.
// The search order is deliberately explicit, because "it did not load" is the most common first-run
// problem with Sciter and a bare dlopen error says nothing useful:
//
//  1. `path`, if given
//  2. the SCITER_LIB environment variable (a file or a directory)
//  3. the directory containing the running executable
//  4. `lib/<platform>/` relative to the current directory, where this repository keeps its copy
//  5. the system library search path (LD_LIBRARY_PATH / PATH / DYLD_LIBRARY_PATH)
//
// On failure `tried` lists every candidate that was attempted, so the caller can print something
// actionable. It is allocated with `allocator`.
load :: proc(
	path := "",
	allocator := context.allocator,
) -> (
	err: Load_Error,
	tried: []string,
) {
	if g_api != nil {
		return .Already_Loaded, nil
	}

	candidates := make([dynamic]string, allocator)

	add :: proc(candidates: ^[dynamic]string, dir_or_file: string) {
		if dir_or_file == "" {
			return
		}
		if filepath.base(dir_or_file) == LIBRARY_NAME {
			append(candidates, strings.clone(dir_or_file, candidates.allocator))
		} else {
			joined, join_err := filepath.join({dir_or_file, LIBRARY_NAME}, candidates.allocator)
			if join_err == nil {
				append(candidates, joined)
			}
		}
	}

	add(&candidates, path)

	if env, has_env := os.lookup_env("SCITER_LIB", context.temp_allocator); has_env {
		add(&candidates, env)
	}

	// Alongside the executable. os.args[0] is what the process was invoked as, so this is best-effort:
	// it resolves to "." for a bare-name invocation, which is a harmless extra candidate.
	if len(os.args) > 0 {
		add(&candidates, filepath.dir(os.args[0]))
	}

	when ODIN_OS == .Windows {
		add(&candidates, "lib/windows/x64")
	} else when ODIN_OS == .Darwin {
		add(&candidates, "lib/macosx")
	} else {
		add(&candidates, "lib/linux/x64")
	}

	// Last resort: bare name, resolved by the system loader.
	append(&candidates, strings.clone(LIBRARY_NAME, allocator))

	library: dynlib.Library
	found: bool
	for candidate in candidates {
		if library, found = dynlib.load_library(candidate); found {
			break
		}
	}
	if !found {
		return .Library_Not_Found, candidates[:]
	}

	symbol, has_symbol := dynlib.symbol_address(library, "SciterAPI")
	if !has_symbol {
		dynlib.unload_library(library)
		return .Missing_Entry_Point, candidates[:]
	}

	table := (cast(Sciter_Api_Ptr)symbol)()
	if table == nil {
		dynlib.unload_library(library)
		return .Null_Api, candidates[:]
	}
	if table.version != EXPECTED_API_VERSION {
		dynlib.unload_library(library)
		return .Version_Mismatch, candidates[:]
	}

	g_library = library
	g_api = table
	return .None, candidates[:]
}

// Releases the shared library. Rarely needed - the engine is normally kept for the life of the process.
unload :: proc() {
	if g_api == nil {
		return
	}
	g_api = nil
	dynlib.unload_library(g_library)
	g_library = {}
}
